input_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results/TTbar_noPU_Embedding_output-smeared
output_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results/TTbar_noPU_Filter_output-smeared
stage_dir: ./
project: LRT_Filter
filter_cut: 0.17200000000000001
overwrite: true
pt_background_min: 0.0
pt_signal_min: 0.0
datatype_names:
- - train
  - val
  - test
datatype_split:
- - 1500
  - 500
  - 1500
endcaps: true
true_edges: layerless_true_edges
noise: true
in_channels: 3
hidden: 1024
nb_layer: 3
emb_channels: 0
batch_size: 1
layernorm: true
batchnorm: false
n_chunks: 8
edges_per_batch: 300000
ratio: 2
weight: 1.6300000000000001
warmup: 800
lr: 0.001
devices: 1
factor: 0.4
patience: 9
regime:
- - non-ci
  - non-ci
max_epochs: 20
callbacks:
- FilterGetPurEff
- FilterBuilder
checkpoint_path: /global/cfs/cdirs/m3443/data/GNNforLRT/lightning_checkpoints/LRT_Filter/version_96/checkpoints/epoch=19-step=30000.ckpt
TAG: Smeared-best
