TAG: HNLPU200-HSSPU200
batch_size: 1
batchnorm: false
callbacks:
- FilterGetPurEff
- FilterBuilder
checkpoint_path: /global/cfs/cdirs/m3443/data/GNNforLRT/bestckpt/forHNL/Filter.ckpt
datatype_names:
- - train
  - val
  - test
datatype_split:
- - null
  - null
  - null
devices: 1
edges_per_batch: 300000
emb_channels: 0
endcaps: true
factor: 0.4
filter_cut: 0.17200000000000001
hidden: 1024
in_channels: 3
input_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results_final/Inference-SampleHSSPU200-ModelHNLPU200-Embed
layernorm: true
log_dir: logging/HNLPU200-HSSPU200
lr: 0.001
max_epochs: 20
n_chunks: 8
nb_layer: 3
noise: true
output_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results_final/Inference-SampleHSSPU200-ModelHNLPU200-Filter
overwrite: true
patience: 9
performance_path: HNLPU200-HSSPU200.yaml
project: LRT_Filter
pt_background_min: 0.0
pt_signal_min: 0.0
ratio: 2
regime:
- - non-ci
  - non-ci
stage_dir: ./
train_split:
- - 0
  - 0
  - 1500
true_edges: layerless_true_edges
warmup: 800
weight: 1.6300000000000001
