TAG: HNLPU200-HSSPU0
batch_size: 1
batchnorm: false
callbacks:
- FilterInferenceCallback
- FilterGetPurEff
- FilterBuilder
checkpoint_path: lightning_checkpoints/LRT_Filter/best/checkpoints/epoch=19-step=40000.ckpt
datatype_names:
- - train
  - val
  - test
datatype_split:
- - 0
  - 0
  - 3000
edges_per_batch: 300000
emb_channels: 0
endcaps: true
factor: 0.4
filter_cut: 0.01
hidden: 512
in_channels: 3
input_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results_final/Inference-SampleHSSPU0-ModelHNLPU200-Embed
layernorm: true
log_dir: logging/HNLPU200-HSSPU0
lr: 0.001
max_epochs: 20
n_chunks: 2
nb_layer: 8
noise: true
output_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results_final/Inference-SampleHSSPU0-ModelHNLPU200-Filter
overwrite: true
patience: 9
performance_path: HNLPU200-HSSPU0.yaml
project: LRT_Filter
pt_background_min: 0.0
pt_signal_min: 0.0
ratio: 2
regime:
- []
true_edges: layerless_true_edges
warmup: 800
weight: 1
