input_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/trackPt1GeV-smeared/HNL_output_PU200_NPZ-testOnly-2
output_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results/SampleHNLPU200_ModelMIXPU200-Embed_inference
stage_dir: ./
project: LRT_Embedding
overwrite: true
pt_signal_min: 0
pt_background_min: 0
train_split:
- - 0 #1500
  - 0 #250
  - 1000 #1000
true_edges: layerless_true_edges
noise: true
in_channels: 3
emb_hidden:
- - 1024
  - 1024
  - 1024
  - 1024
nb_layer: 4
emb_dim: 12
weight: 4
randomisation: 2
batch_size: 1
points_per_batch: 130000
r_test: 0.2
r_train: 0.2
r_val: 0.2
knn: 8
warmup: 4
margin: 0.2
lr: 0.0001
devices: 1 # 2 for 2 gpus
factor: 0.58
patience: 5
regime:
- - rp
  - hnm
max_epochs: 30
checkpoint_path: /global/cfs/cdirs/m3443/data/GNNforLRT/bestckpt/forAll/Embedding_optimized_onHNL.ckpt
callbacks:
- EmbeddingBuilder
TAG: SampleHNLFlatPU_ModelMIXPU200_inference