input_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/trackPt1GeV-smeared/TTbar_DiLep_output_FlatPU_NPZ
output_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results/TTbar_Embedding_output-smeared_FlatPU
stage_dir: ./
project: LRT_Embedding
overwrite: true
pt_signal_min: 0
pt_background_min: 0
train_split:
- - 0
  - 0
  - 2000
true_edges: layerless_true_edges
noise: true
in_channels: 3
emb_hidden:
- - 256
  - 256
  - 256
  - 256
nb_layer: 6
emb_dim: 4
weight: 1.5
randomisation: 2
batch_size: 1
points_per_batch: 100000
r_train: 0.33999999999999997
r_val: 0.33999999999999997
r_test: 0.33999999999999997
knn: 4
warmup: 4
margin: 0.19
lr: 0.0003
devices: 1
factor: 0.58
patience: 10
regime:
- - rp
  - hnm
max_epochs: 20
checkpoint_path: /global/cfs/cdirs/m3443/data/GNNforLRT/bestckpt/forTTBar/Embed.ckpt
callbacks:
- EmbeddingPurEff
- EmbeddingBuilder
TAG: Smeared-best-FlatPU
