TAG: HNLPU200-HSSPU200
batch_size: 1
callbacks:
- GNNEffPur
- GNNBuilder
checkpoint_path: /global/cfs/cdirs/m3443/data/GNNforLRT/bestckpt/forHNL/GNN.ckpt
datatype_names:
- - train
  - val
  - test
datatype_split:
- - null
  - null
  - null
delta_eta: 1.2
devices: 2
edge_cut: 0.334
emb_channels: 0
endcaps: true
factor: 0.3
hidden: 1024
hidden_activation: ReLU
in_channels: 3
input_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results_final/Inference-SampleHSSPU200-ModelHNLPU200-Filter
layernorm: true
log_dir: logging/HNLPU200-HSSPU200
lr: 0.001
max_epochs: 20
n_graph_iters: 4
nb_edge_layer: 4
nb_node_layer: 2
noise: true
output_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results_final/Inference-SampleHSSPU200-ModelHNLPU200-GNN
overwrite: true
patience: 10
performance_path: HNLPU200-HSSPU200.yaml
project: LRT_GNN
pt_background_min: 0.0
pt_signal_min: 0.0
regime:
- []
slack_alert: false
stage_dir: ./
train_split:
- - 0
  - 0
  - 1500
true_edges: layerless_true_edges
warmup: 200
weight: 2.47
