TAG: HNLPU200-HSSPU0
batch_size: 1
callbacks:
- GNNEffPur
- GNNBuilder
checkpoint_path: lightning_checkpoints/LRT_GNN/best/checkpoints/epoch=24-step=50000.ckpt
datatype_names:
- - train
  - val
  - test
datatype_split:
- - 0
  - 0
  - 1000
delta_eta: 1.2
edge_cut: 0.5
emb_channels: 0
endcaps: true
factor: 0.3
hidden: 1024
hidden_activation: ReLU
in_channels: 3
input_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results_final/Inference-SampleHSSPU0-ModelHNLPU200-Filter
layernorm: true
log_dir: logging/HNLPU200-HSSPU0
lr: 0.0001
max_epochs: 25
n_graph_iters: 3
nb_edge_layer: 2
nb_node_layer: 5
noise: true
output_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results_final/Inference-SampleHSSPU0-ModelHNLPU200-GNN
overwrite: true
patience: 10
performance_path: HNLPU200-HSSPU0.yaml
project: LRT_GNN
pt_background_min: 0.0
pt_signal_min: 0.0
regime:
- []
slack_alert: false
true_edges: layerless_true_edges
warmup: 200
weight: 2
