input_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results/TTbar_Filter_output-smeared_FlatPU
output_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results/TTbar_GNN_output-smeared_FlatPU
project: LRT_GNN
edge_cut: 0.334
overwrite: true
pt_background_min: 0.0
pt_signal_min: 0.0
datatype_names:
- - train
  - val
  - test
datatype_split:
- - 0
  - 0
  - 2000
endcaps: true
true_edges: layerless_true_edges
noise: true
in_channels: 3
hidden: 1024
batch_size: 1
n_graph_iters: 4
nb_node_layer: 2
nb_edge_layer: 4
emb_channels: 0
layernorm: true
hidden_activation: ReLU
weight: 2.47
delta_eta: 1.2
warmup: 200
lr: 0.001
factor: 0.3
patience: 10
regime:
- []
max_epochs: 20
devices: 1 #2
slack_alert: false
checkpoint_path: /global/cfs/cdirs/m3443/data/GNNforLRT/lightning_checkpoints/LRT_GNN/version_358/checkpoints/epoch=18-step=14250.ckpt
callbacks:
- GNNEffPur
- GNNBuilder
stage_dir: ./
TAG: Smeared-best-FlatPU
