input_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results/SampleHNLPU200_ModelHNLPU200-Filter-0p7
output_dir: /global/cfs/cdirs/m3443/data/GNNforLRT/results/SampleHSSPU200_ModelHNLPU200-GNN_inference
project: LRT_GNN
edge_cut: 0.7
overwrite: true
pt_background_min: 0.0
pt_signal_min: 0.0
datatype_names:
- - train
  - val
  - test
datatype_split:
- - 1500 #1500
  - 250 #250
  - 1000 #1000
endcaps: true
true_edges: layerless_true_edges
noise: true
in_channels: 3
hidden: 1024
batch_size: 1
n_graph_iters: 3
nb_edge_layer: 2
nb_node_layer: 5
emb_channels: 0
layernorm: true
hidden_activation: ReLU
weight: 2
delta_eta: 1.2
warmup: 200
lr: 0.0001
factor: 0.3
patience: 5
regime:
- []
max_epochs: 30
devices: 1
slack_alert: false
checkpoint_path: /global/cfs/cdirs/m3443/data/GNNforLRT/bestckpt/forHNL/GNN0.ckpt
callbacks:
- GNNEffPur
stage_dir: ./
TAG: SampleHSSPU200_ModelHNLPU200_inference